project:
  type: website
  output-dir: docs
  render:
    - index.qmd
  resources:
    - CNAME
    - .nojekyll
    - slides.pdf
    - claude-dcf-example.xlsx
   

website:
  title: "FMA IITA Presentation"

format:
  html:
    theme: default