project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides16x9.qmd
  resources:
    - CNAME
    - .nojekyll
    - InnovationInTeaching.pdf
   

website:
  title: "FMA 2025 AI Presentation"

format:
  html:
    theme: default